apiVersion: v1
kind: Pod
metadata:
  name: fronteend
  labels:
    app: fronteend
spec:
  containers:
    - name: fronteend
      image: acrimg1.azurecr.io/fronteend:f1
      ports:
        - containerPort: 80
