apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
    - name: mysql
      image: acrimg1.azurecr.io/fronteend:f1
      ports:
        - containerPort: 3306
