apiVersion: v1 
kind: Pod 
metadata: 
  name: backend 
  labels: 
    app: backend 
  annotations: 
    argocd.argoproj.io/sync-options: Force=true,Replace=true 
spec: 
  containers: 
    - name: backend 
      image: acrimg2.azurecr.io/backend:b2
      ports: 
        - containerPort: 8080 
      env: 
        - name: ConnectionStrings__DefaultConnection 
          valueFrom: 
            secretKeyRef: 
              name: backend-db-secret 
              key: ConnectionStrings__DefaultConnection
