apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    app: backend
spec:
  containers:
    - name: backend
      image: acrimg1.azurecr.io/backend:e1
      ports:
        - containerPort: 80
