apiVersion: v1
kind: Pod
metadata:
  name: elarnfront
  labels:
    app: elarnfront
spec:
  containers:
    - name: elarnfront
      image: acrimg1.azurecr.io/elarnfront1:v9
      ports:
        - containerPort: 80
