apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
    - name: mysql
      image: acrimg2.azurecr.io/mysql:v2
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: StrongPass123
        - name: MYSQL_DATABASE
          value: mydb
        - name: MYSQL_USER
          value: myuser
        - name: MYSQL_PASSWORD
          value: mypassword
      ports:
        - containerPort: 3306
