apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    app: mysql   # must match the Pod label
  ports:
    - protocol: TCP
      port: 3306        # Service port
      targetPort: 3306  # Pod containerPort
  type: ClusterIP
