apiVersion: v1
kind: Pod
metadata:
  name: website
  labels:
    app: website
spec:
  containers:
    - name: website
      image: acrimg1.azurecr.io/scheldon:v7
      ports:
        - containerPort: 80
